//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuxuryWatches.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class baiViet
    {
        public int maBV { get; set; }
        public string tenBV { get; set; }
        public System.DateTime ngayDang { get; set; }
        public string tkThanhVien { get; set; }
        public string ndTomTat { get; set; }
        public string hinhDD { get; set; }
        public string noiDungBV { get; set; }
        public bool daDuyet { get; set; }
        public Nullable<int> soLanDoc { get; set; }
        public string biDanh { get; set; }
    
        public virtual taiKhoan taiKhoan { get; set; }
    }
}
