//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuxuryWatches.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hopThu
    {
        public int hopThuID { get; set; }
        public string hoTen { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
        public string noiDung { get; set; }
        public Nullable<System.DateTime> ngayGui { get; set; }
        public bool daDuyet { get; set; }
        public string tkDuyet { get; set; }
        public string ghiChu { get; set; }
    
        public virtual taiKhoan taiKhoan { get; set; }
    }
}
