//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuxuryWatches.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LuxuryWatchesEntities : DbContext
    {
        public LuxuryWatchesEntities()
            : base("name=LuxuryWatchesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hopThu> hopThus { get; set; }
        public virtual DbSet<baiViet> baiViets { get; set; }
        public virtual DbSet<taiKhoan> taiKhoans { get; set; }
        public virtual DbSet<sanPham> sanPhams { get; set; }
        public virtual DbSet<HangSanXuat> HangSanXuats { get; set; }
        public virtual DbSet<loaiSP> loaiSPs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<donHang> donHangs { get; set; }
        public virtual DbSet<chiTietDH> chiTietDHs { get; set; }
    }
}
